# Site settings
title: Workshop Manual HTML/CSS Coding Standards
email: michael.fouquet@me.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
twitter_username: _fookay
github_username:  mfouquet
github:
  repo: https://github.com/mfouquet/workmanship

# Build settings
source: .
exclude: ['Gruntfile.js', 'package.json', node_modules]
markdown: kramdown
sass:
  sass_dir: ../
  style: compressed
